import type { Metadata } from "next";
import "./app.css";
import { GeistSans } from 'geist/font/sans';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className + `bg-gray-200`}>{children}</body>
    </html>
  );
}
